#!/bin/bash
mv /tmp/ betty /tmp/my_first_directory[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C#!/bin/bash
m[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Amv /tmp/betty /tmp/my_first_directory[C[C
